// Namespaced localStorage wrapper — simulates server storage for the prototype
const PREFIX = 'sf_';

export const storage = {
  async get(key) {
    try {
      const raw = localStorage.getItem(PREFIX + key);
      return raw ? { value: raw } : null;
    } catch { return null; }
  },
  async set(key, value) {
    try { localStorage.setItem(PREFIX + key, value); }
    catch (e) { console.error('storage.set error', e); }
  },
  async remove(key) {
    try { localStorage.removeItem(PREFIX + key); }
    catch {}
  },
};

export function uid() {
  return Math.random().toString(36).slice(2, 10) + Date.now().toString(36).slice(-4);
}

function dk(offset = 0) {
  const d = new Date();
  d.setDate(d.getDate() + offset);
  return d.toISOString().slice(0, 10);
}

/* ─── SEED DATA ─── */

export const SEED_FACILITIES = [
  {
    id: 'fac-1',
    name: 'Grand Ballroom',
    type: 'Ballroom',
    description: 'Our flagship event space featuring crystal chandeliers, a 200m² sprung dance floor and capacity for up to 500 guests. Perfect for weddings, galas and large conferences.',
    capacity: 500,
    area: 850,
    baseHourlyRate: 850,
    minBookingHours: 4,
    maxBookingHours: 16,
    locationName: 'Central London Hub',
    city: 'London',
    areaDistrict: 'Westminster',
    address: '12 Carlton Gardens, St. James’s, London SW1Y 5AH',
    postcode: 'SW1Y 5AH',
    travelHint: 'Zone 1 · 3 min walk from Piccadilly Circus & Green Park',
    coordinates: { x: 480, y: 390 },
    eventTypes: ['Wedding', 'Gala', 'Conference', 'Reception', 'Exhibition'],
    amenities: ['PA System', 'Stage (10×6m)', 'Dance Floor', 'Catering Kitchen', 'Bar Setup', 'Lighting Rig', 'Climate Control', 'Breakout Rooms', 'WiFi', 'Wheelchair Access'],
    colorGrad: 'linear-gradient(135deg, #4C1D95 0%, #7C3AED 100%)',
    accentColor: '#A78BFA',
    bufferRules: {
      default:    { setup: 60,  teardown: 90  },
      Wedding:    { setup: 180, teardown: 240 },
      Gala:       { setup: 120, teardown: 180 },
      Conference: { setup: 60,  teardown: 90  },
      Exhibition: { setup: 240, teardown: 240 },
      Reception:  { setup: 90,  teardown: 120 },
    },
    preAuthAmount: 2000,
    openHours: { start: 8, end: 23 },
    availableDays: [0,1,2,3,4,5,6],
    peakMultiplier: 1.3,
    active: true,
    createdAt: Date.now() - 86400000 * 180,
  },
  {
    id: 'fac-2',
    name: 'Conference Suite A',
    type: 'Conference Room',
    description: 'Modern 50-person conference room with state-of-the-art AV equipment, video conferencing and natural lighting. Ideal for corporate events, training and board meetings.',
    capacity: 50,
    area: 120,
    baseHourlyRate: 120,
    minBookingHours: 1,
    maxBookingHours: 12,
    locationName: 'Central London Hub',
    city: 'London',
    areaDistrict: 'Westminster',
    address: '12 Carlton Gardens, St. James’s, London SW1Y 5AH',
    postcode: 'SW1Y 5AH',
    travelHint: 'Zone 1 · 3 min walk from Piccadilly Circus & Green Park',
    coordinates: { x: 480, y: 390 },
    eventTypes: ['Meeting', 'Training', 'Workshop', 'Conference', 'Interview'],
    amenities: ['4K Projector', '75" Display', 'Video Conferencing', 'Whiteboard', 'Coffee Station', 'High-Speed WiFi', 'Flip Charts', 'Wheelchair Access'],
    colorGrad: 'linear-gradient(135deg, #0E7490 0%, #06B6D4 100%)',
    accentColor: '#22D3EE',
    bufferRules: {
      default:    { setup: 15, teardown: 15 },
      Meeting:    { setup: 15, teardown: 15 },
      Training:   { setup: 30, teardown: 30 },
      Workshop:   { setup: 30, teardown: 30 },
      Conference: { setup: 45, teardown: 45 },
      Interview:  { setup: 10, teardown: 10 },
    },
    preAuthAmount: 300,
    openHours: { start: 7, end: 20 },
    availableDays: [1,2,3,4,5],
    peakMultiplier: 1.15,
    active: true,
    createdAt: Date.now() - 86400000 * 120,
  },
  {
    id: 'fac-3',
    name: 'Conference Suite B',
    type: 'Conference Room',
    description: 'Intimate 30-person boardroom with executive leather seating, built-in display and dedicated breakout area. Suited for executive meetings and small workshops.',
    capacity: 30,
    area: 70,
    baseHourlyRate: 80,
    minBookingHours: 1,
    maxBookingHours: 10,
    locationName: 'City Tech Campus',
    city: 'London',
    areaDistrict: 'Shoreditch',
    address: '88 Old Street, Silicon Roundabout, London EC1V 9AX',
    postcode: 'EC1V 9AX',
    travelHint: 'Zone 1 · 1 min from Old Street Tube',
    coordinates: { x: 505, y: 375 },
    eventTypes: ['Meeting', 'Training', 'Workshop', 'Interview'],
    amenities: ['65" Display', 'Teleconference Bridge', 'Whiteboard', 'Coffee Station', 'WiFi', 'Natural Lighting', 'High-Speed WiFi'],
    colorGrad: 'linear-gradient(135deg, #065F46 0%, #10B981 100%)',
    accentColor: '#34D399',
    bufferRules: {
      default:  { setup: 15, teardown: 15 },
      Meeting:  { setup: 10, teardown: 10 },
      Training: { setup: 20, teardown: 20 },
      Workshop: { setup: 20, teardown: 20 },
    },
    preAuthAmount: 200,
    openHours: { start: 7, end: 20 },
    availableDays: [1,2,3,4,5],
    peakMultiplier: 1.1,
    active: true,
    createdAt: Date.now() - 86400000 * 100,
  },
  {
    id: 'fac-4',
    name: 'St. George\'s Cricket Ground',
    type: 'Sports Ground',
    description: 'Premier cricket ground with a full-size turf pitch, practice nets, electronic scoreboard and pavilion with changing facilities. Hosted county matches and international youth fixtures.',
    capacity: 3000,
    area: 18000,
    baseHourlyRate: 400,
    minBookingHours: 3,
    maxBookingHours: 14,
    locationName: 'Surrey Sports & Country Grounds',
    city: 'Guildford',
    areaDistrict: 'Surrey',
    address: 'The Pavilion, Green Park Road, Guildford GU2 7XX',
    postcode: 'GU2 7XX',
    travelHint: '10 min from Guildford Rail Station · Dedicated Parking',
    coordinates: { x: 440, y: 440 },
    eventTypes: ['Match', 'Practice', 'Tournament', 'Coaching Session', 'Community Event'],
    amenities: ['Turf Pitch', '6 Practice Nets', 'Electronic Scoreboard', 'Floodlights', 'Pavilion', 'Changing Rooms', 'Commentary Box', 'Wheelchair Access', 'Parking'],
    colorGrad: 'linear-gradient(135deg, #166534 0%, #22C55E 100%)',
    accentColor: '#4ADE80',
    bufferRules: {
      default:          { setup: 60,  teardown: 60  },
      Match:            { setup: 120, teardown: 60  },
      Tournament:       { setup: 180, teardown: 120 },
      Practice:         { setup: 30,  teardown: 30  },
      'Coaching Session': { setup: 30, teardown: 30 },
      'Community Event': { setup: 90, teardown: 90 },
    },
    preAuthAmount: 1000,
    openHours: { start: 7, end: 21 },
    availableDays: [0,1,2,3,4,5,6],
    peakMultiplier: 1.25,
    active: true,
    createdAt: Date.now() - 86400000 * 200,
  },
  {
    id: 'fac-5',
    name: 'The Ivory Studio',
    type: 'Photography Studio',
    description: 'Professional photography and video production studio with seamless cyclorama walls, professional lighting rigs, makeup station and equipment hire.',
    capacity: 20,
    area: 95,
    baseHourlyRate: 90,
    minBookingHours: 2,
    maxBookingHours: 12,
    locationName: 'MediaCityUK Creative Village',
    city: 'Manchester',
    areaDistrict: 'Salford Quays',
    address: 'Studio Block 4, MediaCityUK, Salford, Manchester M50 2EQ',
    postcode: 'M50 2EQ',
    travelHint: 'Adjacent to MediaCityUK Metrolink · Loading Bay Access',
    coordinates: { x: 330, y: 240 },
    eventTypes: ['Photoshoot', 'Filming', 'Workshop', 'Content Creation', 'Brand Shoot'],
    amenities: ['Cyclorama Wall', 'Lighting Rig (LED)', 'Dressing Room', 'Makeup Station', 'Backdrop Rail', 'Equipment Hire', 'WiFi', 'Props Storage'],
    colorGrad: 'linear-gradient(135deg, #7C2D12 0%, #F97316 100%)',
    accentColor: '#FB923C',
    bufferRules: {
      default:            { setup: 30, teardown: 30 },
      Photoshoot:         { setup: 30, teardown: 30 },
      Filming:            { setup: 60, teardown: 60 },
      Workshop:           { setup: 30, teardown: 30 },
      'Content Creation': { setup: 30, teardown: 30 },
      'Brand Shoot':      { setup: 45, teardown: 45 },
    },
    preAuthAmount: 250,
    openHours: { start: 8, end: 20 },
    availableDays: [0,1,2,3,4,5,6],
    peakMultiplier: 1.2,
    active: true,
    createdAt: Date.now() - 86400000 * 90,
  },
  {
    id: 'fac-6',
    name: 'Rooftop Terrace',
    type: 'Outdoor Venue',
    description: 'Stunning 400m² rooftop terrace with panoramic city views, retractable awning, outdoor bar and built-in heaters. An iconic backdrop for parties, receptions and corporate events.',
    capacity: 150,
    area: 400,
    baseHourlyRate: 250,
    minBookingHours: 3,
    maxBookingHours: 12,
    locationName: 'Birmingham Skyline Lofts',
    city: 'Birmingham',
    areaDistrict: 'Colmore Row',
    address: 'Level 14, 55 Colmore Row, Birmingham B3 2AA',
    postcode: 'B3 2AA',
    travelHint: '3 min walk from Birmingham Snow Hill & New Street',
    coordinates: { x: 380, y: 310 },
    eventTypes: ['Party', 'Reception', 'Corporate Event', 'Product Launch', 'Networking'],
    amenities: ['Panoramic Views', 'Retractable Awning', 'Outdoor Bar', 'Patio Heaters', 'String Lighting', 'Sound System', 'Outdoor Furniture', 'Event Coordinator'],
    colorGrad: 'linear-gradient(135deg, #1E1B4B 0%, #4338CA 100%)',
    accentColor: '#818CF8',
    bufferRules: {
      default:         { setup: 60,  teardown: 90  },
      Party:           { setup: 90,  teardown: 120 },
      Reception:       { setup: 60,  teardown: 90  },
      'Corporate Event': { setup: 75, teardown: 90 },
      'Product Launch':  { setup: 120, teardown: 90 },
      Networking:      { setup: 45,  teardown: 60  },
    },
    preAuthAmount: 500,
    openHours: { start: 10, end: 23 },
    availableDays: [0,4,5,6], // Fri, Sat, Sun, + Mon
    peakMultiplier: 1.4,
    active: true,
    createdAt: Date.now() - 86400000 * 60,
  },
  {
    id: 'fac-7',
    name: 'Stratford Arena & 3G All-Weather Pitch',
    type: 'Sports Ground',
    description: 'Full-size floodlit 3G synthetic turf pitch with covered spectator seating, player tunnels, electronic scoreboard and FA-compliant changing pavilions.',
    capacity: 1200,
    area: 7200,
    baseHourlyRate: 220,
    minBookingHours: 2,
    maxBookingHours: 12,
    locationName: 'Olympic Park Sports Hub',
    city: 'London',
    areaDistrict: 'Stratford',
    address: 'Queen Elizabeth Olympic Park, Stratford, London E20 2ST',
    postcode: 'E20 2ST',
    travelHint: 'Zone 2/3 · Stratford Underground & International Station',
    coordinates: { x: 530, y: 370 },
    eventTypes: ['Match', 'Practice', 'Tournament', 'Community Event', 'Training'],
    amenities: ['3G Pitch', 'Floodlights', 'Spectator Seating', 'Changing Rooms', 'Shower Block', 'Parking', 'Wheelchair Access'],
    colorGrad: 'linear-gradient(135deg, #064E3B 0%, #059669 100%)',
    accentColor: '#10B981',
    bufferRules: {
      default:    { setup: 30, teardown: 30 },
      Match:      { setup: 60, teardown: 45 },
      Tournament: { setup: 90, teardown: 90 },
      Practice:   { setup: 15, teardown: 15 },
    },
    preAuthAmount: 500,
    openHours: { start: 7, end: 22 },
    availableDays: [0,1,2,3,4,5,6],
    peakMultiplier: 1.2,
    active: true,
    createdAt: Date.now() - 86400000 * 45,
  },
  {
    id: 'fac-8',
    name: 'The Glasshouse Atrium',
    type: 'Exhibition Hall',
    description: 'Spectacular triple-height glass exhibition hall overlooking the docks, featuring polished terrazzo flooring, modular rigging, vehicle drive-in access and sound zoning.',
    capacity: 800,
    area: 1200,
    baseHourlyRate: 480,
    minBookingHours: 4,
    maxBookingHours: 16,
    locationName: 'Bristol Harbourside Docks',
    city: 'Bristol',
    areaDistrict: 'Harbourside',
    address: 'Wapping Wharf, Gas Ferry Road, Bristol BS1 6UN',
    postcode: 'BS1 6UN',
    travelHint: '12 min walk from Bristol Temple Meads · Ferry landing nearby',
    coordinates: { x: 290, y: 410 },
    eventTypes: ['Exhibition', 'Product Launch', 'Gala', 'Conference', 'Reception'],
    amenities: ['Vehicle Access', 'Full Rigging Points', 'Terrazzo Flooring', 'Acoustic Ceiling', 'Loading Docks', 'Catering Kitchen', 'WiFi', 'Wheelchair Access'],
    colorGrad: 'linear-gradient(135deg, #312E81 0%, #4F46E5 100%)',
    accentColor: '#6366F1',
    bufferRules: {
      default:        { setup: 90,  teardown: 90  },
      Exhibition:     { setup: 240, teardown: 240 },
      'Product Launch': { setup: 120, teardown: 120 },
      Gala:           { setup: 150, teardown: 150 },
    },
    preAuthAmount: 1500,
    openHours: { start: 8, end: 23 },
    availableDays: [0,1,2,3,4,5,6],
    peakMultiplier: 1.3,
    active: true,
    createdAt: Date.now() - 86400000 * 30,
  },
];

const SEED_BOOKINGS = [
  {
    id: 'bk-1',
    facilityId: 'fac-1',
    facilityName: 'Grand Ballroom',
    date: dk(3),
    startHour: 12,
    durationHours: 8,
    eventType: 'Wedding',
    hirerName: 'Eleanor & James Ashworth',
    hirerEmail: 'ella@ashworthwedding.com',
    hirerPhone: '07700900100',
    attendees: 280,
    notes: 'Platinum wedding package. Bride requires early access from 9am.',
    addOns: [{ id: 'catering', name: 'In-House Catering', price: 4200 }, { id: 'av', name: 'AV Package', price: 600 }],
    status: 'confirmed',
    paymentMode: 'auto',
    paymentStatus: 'paid',
    preAuthHold: { enabled: true, amount: 2000, expiresAt: Date.now() + 86400000 * 10, status: 'held' },
    baseAmount: 8160,
    addOnTotal: 4800,
    discount: 0,
    totalAmount: 12960,
    invoiceId: 'INV-2026-0031',
    createdAt: Date.now() - 86400000 * 14,
    confirmedAt: Date.now() - 86400000 * 13,
    userId: 'u2',
  },
  {
    id: 'bk-2',
    facilityId: 'fac-2',
    facilityName: 'Conference Suite A',
    date: dk(1),
    startHour: 9,
    durationHours: 4,
    eventType: 'Training',
    hirerName: 'TechCorp Ltd',
    hirerEmail: 'events@techcorp.co.uk',
    hirerPhone: '02071234567',
    attendees: 35,
    notes: 'All-day DevOps workshop. Need 30 min setup.',
    addOns: [{ id: 'coffee', name: 'Coffee & Catering', price: 180 }],
    status: 'confirmed',
    paymentMode: 'manual',
    paymentStatus: 'invoiced',
    preAuthHold: { enabled: false },
    baseAmount: 480,
    addOnTotal: 180,
    discount: 0,
    totalAmount: 660,
    invoiceId: 'INV-2026-0032',
    createdAt: Date.now() - 86400000 * 5,
    confirmedAt: Date.now() - 86400000 * 4,
    userId: 'u3',
  },
  {
    id: 'bk-3',
    facilityId: 'fac-4',
    facilityName: 'St. George\'s Cricket Ground',
    date: dk(5),
    startHour: 10,
    durationHours: 8,
    eventType: 'Match',
    hirerName: 'Westfield Cricket Club',
    hirerEmail: 'secretary@westfieldcc.org',
    hirerPhone: '07700900201',
    attendees: 200,
    notes: 'County league fixture. Requires floodlights from 5pm.',
    addOns: [{ id: 'scorer', name: 'Official Scorer', price: 150 }, { id: 'pavilion', name: 'Pavilion Hire', price: 200 }],
    status: 'pending_approval',
    paymentMode: 'manual',
    paymentStatus: 'pending',
    preAuthHold: { enabled: true, amount: 1000, expiresAt: Date.now() + 86400000 * 5, status: 'held' },
    baseAmount: 3840,
    addOnTotal: 350,
    discount: 0,
    totalAmount: 4190,
    invoiceId: null,
    createdAt: Date.now() - 86400000 * 1,
    confirmedAt: null,
    userId: 'u1',
  },
  {
    id: 'bk-4',
    facilityId: 'fac-5',
    facilityName: 'The Ivory Studio',
    date: dk(2),
    startHour: 10,
    durationHours: 4,
    eventType: 'Photoshoot',
    hirerName: 'Nova Creative Agency',
    hirerEmail: 'studio@novacreative.co.uk',
    hirerPhone: '07700900302',
    attendees: 8,
    notes: 'Campaign shoot for fashion brand. White backdrop required.',
    addOns: [{ id: 'lighting', name: 'Lighting Kit Hire', price: 120 }],
    status: 'confirmed',
    paymentMode: 'auto',
    paymentStatus: 'paid',
    preAuthHold: { enabled: false },
    baseAmount: 360,
    addOnTotal: 120,
    discount: 0,
    totalAmount: 480,
    invoiceId: 'INV-2026-0033',
    createdAt: Date.now() - 86400000 * 3,
    confirmedAt: Date.now() - 86400000 * 2,
    userId: 'u1',
  },
  {
    id: 'bk-5',
    facilityId: 'fac-6',
    facilityName: 'Rooftop Terrace',
    date: dk(7),
    startHour: 18,
    durationHours: 5,
    eventType: 'Party',
    hirerName: 'Marcus Beaumont',
    hirerEmail: 'marcus.b@email.com',
    hirerPhone: '07700900403',
    attendees: 80,
    notes: '40th birthday party. DJ from 8pm. No catering needed.',
    addOns: [{ id: 'bar', name: 'Premium Bar Package', price: 800 }],
    status: 'pending_approval',
    paymentMode: 'auto',
    paymentStatus: 'pending',
    preAuthHold: { enabled: true, amount: 500, expiresAt: Date.now() + 86400000 * 7, status: 'held' },
    baseAmount: 1575,
    addOnTotal: 800,
    discount: 0,
    totalAmount: 2375,
    invoiceId: null,
    createdAt: Date.now() - 7200000,
    confirmedAt: null,
    userId: 'u2',
  },
  {
    id: 'bk-6',
    facilityId: 'fac-1',
    facilityName: 'Grand Ballroom',
    date: dk(10),
    startHour: 9,
    durationHours: 6,
    eventType: 'Conference',
    hirerName: 'FinTech Summit 2026',
    hirerEmail: 'organiser@fintechsummit.co.uk',
    hirerPhone: '020 7654 3210',
    attendees: 400,
    notes: 'Annual summit. 3 breakout rooms also required.',
    addOns: [{ id: 'av', name: 'Full AV Package', price: 1200 }, { id: 'catering', name: 'Working Lunch Catering', price: 2400 }],
    status: 'confirmed',
    paymentMode: 'manual',
    paymentStatus: 'invoiced',
    preAuthHold: { enabled: true, amount: 2000, expiresAt: Date.now() + 86400000 * 20, status: 'held' },
    baseAmount: 5967,
    addOnTotal: 3600,
    discount: 0.05,
    totalAmount: 9077,
    invoiceId: 'INV-2026-0034',
    createdAt: Date.now() - 86400000 * 20,
    confirmedAt: Date.now() - 86400000 * 19,
    userId: 'u3',
  },
  {
    id: 'bk-7',
    facilityId: 'fac-2',
    facilityName: 'Conference Suite A',
    date: dk(0),
    startHour: 14,
    durationHours: 3,
    eventType: 'Meeting',
    hirerName: 'Green Capital Partners',
    hirerEmail: 'office@greencap.com',
    hirerPhone: '020 3456 7890',
    attendees: 12,
    notes: '',
    addOns: [],
    status: 'cancelled',
    paymentMode: 'auto',
    paymentStatus: 'refunded',
    preAuthHold: { enabled: false },
    baseAmount: 360,
    addOnTotal: 0,
    discount: 0,
    totalAmount: 360,
    invoiceId: 'INV-2026-0029',
    createdAt: Date.now() - 86400000 * 7,
    confirmedAt: Date.now() - 86400000 * 6,
    userId: 'u1',
  },
  {
    id: 'bk-8',
    facilityId: 'fac-3',
    facilityName: 'Conference Suite B',
    date: dk(1),
    startHour: 9,
    durationHours: 2,
    eventType: 'Interview',
    hirerName: 'Meridian Recruitment',
    hirerEmail: 'admin@meridianrec.co.uk',
    hirerPhone: '07700900501',
    attendees: 6,
    notes: 'Interview panel. Confidential.',
    addOns: [],
    status: 'confirmed',
    paymentMode: 'auto',
    paymentStatus: 'paid',
    preAuthHold: { enabled: false },
    baseAmount: 160,
    addOnTotal: 0,
    discount: 0,
    totalAmount: 160,
    invoiceId: 'INV-2026-0035',
    createdAt: Date.now() - 86400000 * 2,
    confirmedAt: Date.now() - 86400000 * 1,
    userId: 'u2',
  },
  {
    id: 'bk-today-1',
    facilityId: 'fac-1',
    facilityName: 'Grand Ballroom',
    date: dk(0),
    startHour: 10,
    durationHours: 4,
    eventType: 'Conference',
    hirerName: 'Global FinTech Keynote',
    hirerEmail: 'summit@fintechglobal.com',
    hirerPhone: '02079460111',
    attendees: 220,
    notes: 'Main keynote & plenary session. Full stage AV setup.',
    addOns: [{ id: 'av', name: 'AV Package', price: 600 }],
    status: 'confirmed',
    paymentMode: 'auto',
    paymentStatus: 'paid',
    preAuthHold: { enabled: true, amount: 1500, expiresAt: Date.now() + 86400000 * 5, status: 'held' },
    baseAmount: 3200,
    addOnTotal: 600,
    discount: 0,
    totalAmount: 3800,
    invoiceId: 'INV-2026-0040',
    createdAt: Date.now() - 86400000 * 3,
    confirmedAt: Date.now() - 86400000 * 2,
    userId: 'u2',
  },
  {
    id: 'bk-today-2',
    facilityId: 'fac-4',
    facilityName: "St. George's Cricket Ground",
    date: dk(0),
    startHour: 8,
    durationHours: 3,
    eventType: 'Maintenance / Service',
    hirerName: 'Internal Grounds Team',
    hirerEmail: 'grounds@spaceflow.internal',
    hirerPhone: '',
    attendees: 0,
    notes: 'Turf rolling, moisture reading and crease repainting.',
    addOns: [],
    status: 'confirmed',
    isMaintenance: true,
    paymentMode: 'complimentary',
    paymentStatus: 'waived',
    preAuthHold: { enabled: false },
    baseAmount: 0,
    addOnTotal: 0,
    discount: 0,
    totalAmount: 0,
    invoiceId: null,
    createdAt: Date.now() - 86400000 * 1,
    confirmedAt: Date.now() - 86400000 * 1,
    userId: 'admin',
  },
  {
    id: 'bk-today-3',
    facilityId: 'fac-2',
    facilityName: 'Conference Suite A',
    date: dk(0),
    startHour: 15,
    durationHours: 3,
    eventType: 'Meeting',
    hirerName: 'Green Capital Partners',
    hirerEmail: 'office@greencap.com',
    hirerPhone: '02034567890',
    attendees: 14,
    notes: 'Q3 Board Review. Coffee & refreshments required.',
    addOns: [{ id: 'coffee', name: 'Coffee & Catering', price: 120 }],
    status: 'confirmed',
    paymentMode: 'manual',
    paymentStatus: 'invoiced',
    preAuthHold: { enabled: false },
    baseAmount: 360,
    addOnTotal: 120,
    discount: 0,
    totalAmount: 480,
    invoiceId: 'INV-2026-0041',
    createdAt: Date.now() - 86400000 * 2,
    confirmedAt: Date.now() - 86400000 * 1,
    userId: 'u3',
  },
  {
    id: 'bk-today-4',
    facilityId: 'fac-5',
    facilityName: 'The Ivory Studio',
    date: dk(0),
    startHour: 14,
    durationHours: 4,
    eventType: 'Photoshoot',
    hirerName: 'Vogue Autumn Editorial',
    hirerEmail: 'production@vogue.co.uk',
    hirerPhone: '02078889999',
    attendees: 10,
    notes: 'Cover shoot. Request cyclorama repainted.',
    addOns: [{ id: 'lighting', name: 'Lighting Kit Hire', price: 150 }],
    status: 'pending_approval',
    paymentMode: 'auto',
    paymentStatus: 'pending',
    preAuthHold: { enabled: true, amount: 400, expiresAt: Date.now() + 86400000 * 3, status: 'held' },
    baseAmount: 360,
    addOnTotal: 150,
    discount: 0,
    totalAmount: 510,
    invoiceId: null,
    createdAt: Date.now() - 3600000 * 2,
    confirmedAt: null,
    userId: 'u1',
  },
];

const SEED_USERS = [
  { id: 'u1', name: 'Alex Holt', email: 'alex@demo.com', passHash: 'sf_hash_alex', role: 'hirer', createdAt: Date.now() - 86400000 * 60 },
  { id: 'u2', name: 'Sofia Patel', email: 'sofia@demo.com', passHash: 'sf_hash_sofia', role: 'hirer', createdAt: Date.now() - 86400000 * 30 },
  { id: 'u3', name: 'Venue Manager', email: 'admin@spaceflow.com', passHash: 'sf_hash_admin', role: 'admin', createdAt: Date.now() - 86400000 * 180 },
  { id: 'u4', name: 'James Crew', email: 'james@demo.com', passHash: 'sf_hash_james', role: 'staff', createdAt: Date.now() - 86400000 * 10 },
];

const SEED_SETTINGS = {
  venueName: 'The Grand Space',
  currency: 'GBP',
  confirmationMode: 'manual', // 'auto' | 'manual'
  invoicePrefix: 'INV-2026-',
  defaultPreAuthDays: 7,
  memberDiscount: 10,
  earlyBookingDiscount: 5,
  earlyBookingDays: 30,
  taxRate: 20,
};

export async function seedDemoData() {
  const existing = await storage.get('bookings');
  if (existing && existing.value) {
    try {
      const parsed = JSON.parse(existing.value);
      if (!parsed.some(b => b.id === 'bk-today-1')) {
        const merged = [...parsed, ...SEED_BOOKINGS.filter(sb => !parsed.some(p => p.id === sb.id))];
        await storage.set('bookings', JSON.stringify(merged));
      }
    } catch {}
  } else {
    await storage.set('bookings', JSON.stringify(SEED_BOOKINGS));
  }

  // Ensure facilities have multi-location fields & new sites
  const existingFacs = await storage.get('facilities');
  if (existingFacs && existingFacs.value) {
    try {
      const parsedFacs = JSON.parse(existingFacs.value);
      if (!parsedFacs[0]?.locationName || !parsedFacs.some(f => f.id === 'fac-7')) {
        const mergedFacs = SEED_FACILITIES.map(sf => {
          const found = parsedFacs.find(p => p.id === sf.id);
          return found ? { ...sf, ...found, locationName: sf.locationName, city: sf.city, address: sf.address, travelHint: sf.travelHint, areaDistrict: sf.areaDistrict, postcode: sf.postcode, coordinates: sf.coordinates } : sf;
        });
        await storage.set('facilities', JSON.stringify(mergedFacs));
      }
    } catch {}
  } else {
    await storage.set('facilities', JSON.stringify(SEED_FACILITIES));
  }

  const existingSettings = await storage.get('settings');
  if (!existingSettings || !existingSettings.value) {
    await storage.set('settings', JSON.stringify(SEED_SETTINGS));
  }

  const usersExist = await storage.get('users');
  if (!usersExist || !usersExist.value) {
    await storage.set('users', JSON.stringify(SEED_USERS));
    await storage.set('my-booking-ids', JSON.stringify(['bk-3', 'bk-4', 'bk-5']));
  }
}

export async function hashPassword(pw) {
  try {
    const enc = new TextEncoder().encode(pw);
    const buf = await window.crypto.subtle.digest('SHA-256', enc);
    return Array.from(new Uint8Array(buf)).map(b => b.toString(16).padStart(2, '0')).join('');
  } catch {
    let h = 0;
    for (let i = 0; i < pw.length; i++) h = (h * 31 + pw.charCodeAt(i)) >>> 0;
    return 'fallback' + h.toString(16);
  }
}

const DEMO_PASSWORDS = { 'alex@demo.com': 'demo123', 'sofia@demo.com': 'demo123', 'admin@spaceflow.com': 'demo123', 'james@demo.com': 'demo123' };
const DEMO_HASHES    = { 'alex@demo.com': 'sf_hash_alex', 'sofia@demo.com': 'sf_hash_sofia', 'admin@spaceflow.com': 'sf_hash_admin', 'james@demo.com': 'sf_hash_james' };

export async function checkLogin(email, pw) {
  if (DEMO_PASSWORDS[email] && DEMO_PASSWORDS[email] === pw) return DEMO_HASHES[email];
  return await hashPassword(pw);
}


